# Generated by Django 4.2 on 2024-03-13 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewfather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='name',
        ),
    ]
