# Generated by Django 5.0 on 2024-03-27 12:49

import ninkasi.brewfather.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewfather', '0002_remove_recipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='bf_id',
            field=models.CharField(choices=ninkasi.brewfather.models.recipe_vocab, max_length=100),
        ),
    ]
