from django.utils.translation import gettext_lazy as _
from django.http import HttpResponseRedirect
from django.forms import inlineformset_factory, HiddenInput
from django.forms.models import modelform_factory
from django.urls import reverse
from django.contrib.contenttypes.forms import generic_inlineformset_factory
from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from .base import CreateView, UpdateView, DetailView
from ..models.brew import Brew
from ..models.batch import Batch
from ..models.metaphase import MetaPhase
from ..models.malt import MaltMap, Malt, MaltProduct

# remove later
from ..models.recipe import Recipe


class BrewDetailView(DetailView):

    """ Add phase vocab. TODO: could be a template_tag I guess """

    model = Brew
    can_log = True

    def phase_vocab(self):

        """ List phases defined for this system """

        return MetaPhase.objects.filter(parents__model="brew")


class BrewCreateView(CreateView):

    model = Brew

    def get_initial(self):

        """ Get initial form fields """

        if self.kwargs.get('batch'):
            return {'batch': Batch.objects.get(pk=self.kwargs['batch'])}

        return {}


class BrewUpdateView(UpdateView):

    model = Brew

    def get_form(self, form_class=None):

        form = super().get_form(form_class=form_class)

        form.fields['batch'].widget = HiddenInput()

        return form


class BrewImportPhasesView(DetailView):

    """ Get all brew phases from brewed beer """

    model = Brew

    @property
    def success_url(self):

        return reverse("view", kwargs={'pk': self.get_object().pk,
                                       'model': 'brew'})

    def get(self, request, *args, **kwargs):

        """ Shortcut to import of phases from recipe provided """

        if request.GET.get('recipe'):

            self.get_object().import_phases(request.GET['recipe'])
        else:
            messages.error(self.request, _("Recipe to import not provided."))

        return HttpResponseRedirect(self.success_url)


class BrewImportMaterialsView(DetailView):

    """ Get all brew materials from recipe """

    model = Brew
    template_name = "brew_importmaterials.html"

    @property
    def success_url(self):

        return reverse("view", kwargs={'pk': self.get_object().pk,
                                       'model': 'brew'})

    def list_to_malts(self):

        return Malt.objects.all()

    def list_import_malts(self):

        """ Return a list of the ingredients to import. """

        recipe_id = self.request.GET['recipe']

        recipe = self.get_object().batch.beer.get_recipe(recipe_id)

        return [
            {'name': mp.name,
             'amount': mp.amount,
             'unit': mp.unit}
            for mp in recipe.list_ingredients() if mp.type == "Grain"
        ]

    def get_import_map(self):

        """ Create suggested mapping """

        import_map = {}

        for ingredient in self.list_import_malts():

            if MaltMap.objects.filter(from_malt=ingredient['name']).exists():

                import_map[ingredient['name']] = MaltMap.objects.get(
                    from_malt=ingredient['name']).to_malt.id
            else:
                import_map[ingredient['name']] = None

        return import_map

    def post(self, request, *args, **kwargs):

        """ Map malts of remote recipe to Ninkasi base malts """

        brew = self.get_object()

        brew.brewmaterial_set.all().delete()

        for imalt in self.list_import_malts():

            if request.POST.get(f"{imalt['name']}_new_malt", None):
                malt = Malt.objects.create(
                    name=request.POST[f"{imalt['name']}_new_malt"]
                )
                MaltMap.objects.create(
                    from_malt=imalt['name'], to_malt=malt
                )
                brew.brewmaterial_set.create(
                    amount=imalt['amount'],
                    unit=imalt['unit'],
                    material=malt
                )

            if request.POST.get(f"{imalt['name']}_to_malt", None):

                to_malt = Malt.objects.get(
                    pk=int(request.POST[f"{imalt['name']}_to_malt"])
                )

                MaltMap.objects.update_or_create(
                    from_malt=imalt['name'],
                    to_malt=to_malt
                )
                brew.brewmaterial_set.create(
                    amount=imalt['amount'],
                    unit=imalt['unit'],
                    material=to_malt
                )

        return HttpResponseRedirect(self.success_url)


class BrewChecks(BrewDetailView):

    """Listing of qualitychecks related to this brew, generated by
    it's phases. """

    template_name = "brew_checks.html"

    def list_qcs(self):

        """Specify target form for the brew. This is defined by the
        brew phases. Each form needs to be saved seperately.

        """

        return self.object.brewqualitycheck_set.all()
