"""
Django settings for ninkasi project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'eeG6ru7hoom3oC5aethoob8d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'bootstrap4',
    'ninkasi',
    'ninkasi.brewfather',
    'ninkasi.bjcp'
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ninkasi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ninkasi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': './db.sqlite3',
    }
}


# Local cache during DEV, to prevent API overload.
#
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache"
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

APV_NS = 'django.contrib.auth.password_validation'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': f"{ APV_NS }.UserAttributeSimilarityValidator",
    },
    {
        'NAME': f"{ APV_NS }.MinimumLengthValidator",
    },
    {
        'NAME': f"{ APV_NS }..CommonPasswordValidator",
    },
    {
        'NAME': f"{ APV_NS }..NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

BOOTSTRAP4 = {
    "css_url": {
        "href": "/static/bootstrap4/css/bootstrap.css"
    },
    'include_jquery': True,
    "javascript_url": {
        "url": "/static/bootstrap4/js/bootstrap.bundle.js"
    },
    "jquery_url": {
        "url": "/static/bootstrap4/js/jquery-3.2.1.js"
    }
}


# BEGIN Ninkasi variables
#
# RECIPE_MODEL = "brewfather.Recipe"
# RECIPE_MODEL = "ninkasi.Recipe"

# When no recipe is set, use the default
#
DEFAULT_PROCESSING_TIME = "30d"

DEFAULT_BREW_TIME = "8h"

#
# END Ninkasi variables


# BEGIN BrewFather settings
#

# Bf doesn't account for startup, filter, whilrpool and transfer
#
BF_PROCESSING_TIME_OFFSET = 30 + 150 + 15 + 30

BF_FILTER_TIME = "90m"

BF_SPARGE_TIME = "60m"

BF_USER_ID = ""

BF_API_KEY = ""
#
# END BrewFather settings


# BEGIN BJCP
#

BJCP_API_URL = "https://www.api-bjcp.com/graphql"

#
# END BJCP

try:
    from .local_settings import *
except ModuleNotFoundError:
    pass
