# Generated by Django 5.0 on 2024-06-20 15:48

import django.db.models.deletion
import ninkasi.api
import ninkasi.milestones
import ninkasi.models.beer
import ninkasi.models.fields
import ninkasi.models.qualitycheck
import ninkasi.models.task
import ninkasi.ordered
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.CharField(max_length=100, unique=True, verbose_name='Nr')),
                ('volume_projected', models.FloatField(verbose_name='Planned volume')),
                ('date', models.DateField()),
                ('date_mode', models.SmallIntegerField(choices=[(0, 'Start'), (1, 'Delivery')])),
                ('color', ninkasi.models.fields.ColorField(blank=True, max_length=7, null=True, verbose_name='Color')),
            ],
            options={
                'verbose_name_plural': 'Batches',
                'ordering': ['nr'],
            },
            bases=(models.Model, ninkasi.ordered.OrderedContainer, ninkasi.milestones.MilestoneProviderModel),
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('volume', models.FloatField()),
                ('ttype', models.SmallIntegerField(choices=[(0, 'Fermentation'), (1, 'BBT'), (2, 'Lagering')], default=0, verbose_name='Type')),
            ],
            options={
                'verbose_name_plural': 'Tanks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.style')),
                ('description', models.TextField()),
                ('recipes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.recipe')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Temperature')),
                ('duration', ninkasi.models.fields.DurationField(max_length=10, verbose_name='Duration')),
                ('order', models.SmallIntegerField(default=0, editable=False)),
            ],
            options={
                'ordering': ['order'],
            },
            bases=(models.Model, ninkasi.api.Step),
        ),
        migrations.CreateModel(
            name='Brewhouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('volume', models.FloatField()),
                ('warmup', models.SmallIntegerField(help_text='Time in minutes needed for 1 degree C warmup.', verbose_name='Warmup time per degree C')),
                ('next_brew_delay', ninkasi.models.fields.DurationField(help_text='Minimal time needed before the next brew can be started.', max_length=10, verbose_name='Minimal brewtime before next brew')),
                ('filter_loss', models.SmallIntegerField(help_text='Amount of wordt lost in filter dead space.', verbose_name='Amount lost in filter')),
                ('spent_grain_loss', models.SmallIntegerField(verbose_name='Spent grain loss per Kg')),
                ('whirlpool_loss', models.SmallIntegerField(help_text='Amount of wordt lost in whirlpool dead space.', verbose_name='Amount lost in whirlpool')),
                ('evaporation_rate', models.SmallIntegerField(help_text='Loss during boil in L/h', verbose_name='Amount lost in boil')),
            ],
            options={
                'verbose_name_plural': 'Brewhouses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('synonyms', models.CharField(blank=True, max_length=255, null=True, verbose_name='Synonyms')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('category', models.ManyToManyField(blank=True, to='ninkasi.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('priority', models.SmallIntegerField(choices=[(1, 'High'), (3, 'Medium'), (5, 'Low')], default=3)),
                ('status', models.SmallIntegerField(choices=[(0, 'Open'), (1, 'Done'), (2, 'Cancelled'), (3, 'Forfeited')], default=0, editable=False)),
                ('estimated_time', ninkasi.models.fields.DurationField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField()),
                ('metaphase', models.CharField(editable=False, max_length=100)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'Phases',
                'ordering': ['order'],
            },
            bases=(ninkasi.api.Phase, models.Model, ninkasi.models.task.TaskFactory),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('volume', models.SmallIntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', ninkasi.models.fields.MilestoneField(choices=ninkasi.models.qualitycheck.milestone_vocab, max_length=100)),
                ('offset', ninkasi.models.fields.DurationField(default='0m', help_text='Offset to milestone. Use negative amounts to specify before', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Quantities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('volume', models.SmallIntegerField(verbose_name='Volume')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
            },
            bases=(models.Model, ninkasi.api.Recipe, ninkasi.ordered.OrderedContainer),
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('description', models.TextField()),
                ('color', ninkasi.models.fields.IntRangeField(max_length=10, verbose_name='Color')),
                ('source', models.CharField(max_length=50, verbose_name='Source')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(models.Model, ninkasi.api.Style),
        ),
        migrations.CreateModel(
            name='BBT',
            fields=[
                ('tank_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ninkasi.tank')),
            ],
            options={
                'verbose_name_plural': 'BBTs',
            },
            bases=('ninkasi.tank',),
        ),
        migrations.CreateModel(
            name='CCT',
            fields=[
                ('tank_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ninkasi.tank')),
                ('cone_loss', models.SmallIntegerField(verbose_name='Amount lost in cone.')),
            ],
            options={
                'verbose_name_plural': 'CCTs',
            },
            bases=('ninkasi.tank', ninkasi.milestones.MilestoneProviderModel),
        ),
        migrations.CreateModel(
            name='LagerTank',
            fields=[
                ('tank_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ninkasi.tank')),
            ],
            options={
                'verbose_name_plural': 'Lager tanks',
            },
            bases=('ninkasi.tank',),
        ),
        migrations.CreateModel(
            name='BatchContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('volume', models.FloatField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.batch')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.tank')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='tank',
            field=models.ManyToManyField(through='ninkasi.BatchContainer', to='ninkasi.tank'),
        ),
        migrations.AddField(
            model_name='batch',
            name='beer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.beer'),
        ),
        migrations.CreateModel(
            name='BoilStep',
            fields=[
                ('step_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ninkasi.step')),
            ],
            options={
                'abstract': False,
            },
            bases=('ninkasi.step',),
        ),
        migrations.CreateModel(
            name='FermentationStep',
            fields=[
                ('step_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ninkasi.step')),
            ],
            options={
                'abstract': False,
            },
            bases=('ninkasi.step',),
        ),
        migrations.CreateModel(
            name='FilterStep',
            fields=[
                ('step_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ninkasi.step')),
            ],
            options={
                'abstract': False,
            },
            bases=('ninkasi.step',),
        ),
        migrations.CreateModel(
            name='MashStep',
            fields=[
                ('step_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ninkasi.step')),
            ],
            options={
                'abstract': False,
            },
            bases=('ninkasi.step',),
        ),
        migrations.CreateModel(
            name='MaturationStep',
            fields=[
                ('step_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ninkasi.step')),
            ],
            options={
                'abstract': False,
            },
            bases=('ninkasi.step',),
        ),
        migrations.CreateModel(
            name='Brew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Time')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.batch')),
                ('brewhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.brewhouse')),
            ],
            options={
                'verbose_name_plural': 'Brews',
                'ordering': ['batch__nr', 'date'],
            },
            bases=(models.Model, ninkasi.ordered.OrderedContainer, ninkasi.milestones.MilestoneProviderModel),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ninkasi.material')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=('ninkasi.material',),
        ),
        migrations.CreateModel(
            name='BrewMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('batchnr', models.CharField(max_length=100, verbose_name='Batch Nr')),
                ('brew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.brew')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.material')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='brew',
            name='material',
            field=models.ManyToManyField(through='ninkasi.BrewMaterial', to='ninkasi.material'),
        ),
        migrations.CreateModel(
            name='BatchMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('batchnr', models.CharField(max_length=100, verbose_name='Batch Nr')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.batch')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.material')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='material',
            field=models.ManyToManyField(through='ninkasi.BatchMaterial', to='ninkasi.material'),
        ),
        migrations.CreateModel(
            name='MetaPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('default_step', models.ForeignKey(limit_choices_to=models.Q(('app_label', 'ninkasi'), ('model__icontains', 'step')), on_delete=django.db.models.deletion.CASCADE, related_name='default_metaphase', to='contenttypes.contenttype')),
                ('parents', models.ManyToManyField(limit_choices_to=models.Q(('app_label', 'ninkasi'), ('model__in', ['batch', 'brew', 'recipe'])), related_name='mp_parents', to='contenttypes.contenttype')),
                ('steps', models.ManyToManyField(limit_choices_to=models.Q(('app_label', 'ninkasi'), ('model__icontains', 'step')), to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'MetaPhases',
                'ordering': ['name'],
            },
            bases=(models.Model, ninkasi.milestones.MilestoneProvider),
        ),
        migrations.CreateModel(
            name='BrewhouseDelays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay', ninkasi.models.fields.DurationField(help_text='Specify the delay as a duration BEFORE the phase can start', max_length=10)),
                ('brewhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.brewhouse')),
                ('metaphase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.metaphase')),
            ],
            options={
                'verbose_name_plural': 'Delays',
            },
        ),
        migrations.AddField(
            model_name='brewhouse',
            name='delays',
            field=models.ManyToManyField(through='ninkasi.BrewhouseDelays', to='ninkasi.metaphase'),
        ),
        migrations.CreateModel(
            name='MilestoneScheduledTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ninkasi.task')),
                ('precision', ninkasi.models.fields.DurationField(help_text='How much slack is allowed around the specified time?', max_length=10)),
                ('milestone', ninkasi.models.fields.MilestoneField(choices=ninkasi.models.task.milestone_vocab, max_length=100)),
                ('offset', ninkasi.models.fields.DurationField(blank=True, help_text='Offset from time of milestone. Use negative durations to specify before the milestone', max_length=10, null=True)),
            ],
            bases=('ninkasi.task', ninkasi.models.task.TaskFactory),
        ),
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ninkasi.task')),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('precision', ninkasi.models.fields.DurationField(max_length=10)),
            ],
            bases=('ninkasi.task',),
        ),
        migrations.AddField(
            model_name='tank',
            name='maintenance_schema',
            field=models.ManyToManyField(blank=True, null=True, to='ninkasi.task'),
        ),
        migrations.AddField(
            model_name='brewhouse',
            name='maintenance_schema',
            field=models.ManyToManyField(blank=True, null=True, to='ninkasi.task'),
        ),
        migrations.AddField(
            model_name='step',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.phase'),
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.SmallIntegerField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.batch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.product')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='product',
            field=models.ManyToManyField(through='ninkasi.Deliverable', to='ninkasi.product'),
        ),
        migrations.CreateModel(
            name='BrewQualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projected', models.FloatField(blank=True, null=True)),
                ('margin', models.FloatField(default=0)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('actual', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('brew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.brew')),
                ('qc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.qualitycheck')),
            ],
        ),
        migrations.AddField(
            model_name='brew',
            name='checks',
            field=models.ManyToManyField(through='ninkasi.BrewQualityCheck', to='ninkasi.qualitycheck'),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='quantity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.quantity'),
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('date', models.DateTimeField(verbose_name='Time')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Notes')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.step')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='StepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End time')),
                ('step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.step')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('date', models.DateTimeField(verbose_name='Date (actual)')),
                ('end_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date to')),
                ('volume', models.SmallIntegerField(blank=True, null=True, verbose_name='Volume')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.tank')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('abbreviation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Abbreviation')),
                ('subs', models.ManyToManyField(through='ninkasi.Conversion', to='ninkasi.unit')),
            ],
            options={
                'verbose_name_plural': 'Units',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='quantity',
            name='units',
            field=models.ManyToManyField(blank=True, null=True, to='ninkasi.unit'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.unit'),
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('time', models.DateTimeField(verbose_name='Time')),
                ('value', models.FloatField()),
                ('notes', models.TextField(blank=True, max_length=200, null=True, verbose_name='Notes')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.quantity')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.unit')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.AddField(
            model_name='conversion',
            name='from_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.unit'),
        ),
        migrations.AddField(
            model_name='conversion',
            name='to_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_unit', to='ninkasi.unit'),
        ),
        migrations.AddField(
            model_name='brewmaterial',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.unit'),
        ),
        migrations.AddField(
            model_name='batchmaterial',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.unit'),
        ),
        migrations.CreateModel(
            name='Fermentable',
            fields=[
                ('ingredient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ninkasi.ingredient')),
            ],
            bases=('ninkasi.ingredient',),
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('addition_time', models.FloatField(blank=True, null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.recipe')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.unit')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(through='ninkasi.RecipeIngredient', to='ninkasi.ingredient'),
        ),
        migrations.CreateModel(
            name='RepeatedScheduledTask',
            fields=[
                ('scheduledtask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ninkasi.scheduledtask')),
                ('frequency', models.SmallIntegerField(choices=[(0, 'Daily'), (1, 'Weekly'), (2, 'Monthly'), (3, 'Yearly')])),
                ('frequency_modifier', models.SmallIntegerField(default=1, help_text="For instance, to specify 'every two weeks'")),
            ],
            bases=('ninkasi.scheduledtask', ninkasi.models.task.TaskFactory),
        ),
        migrations.CreateModel(
            name='MilestoneTaskSub',
            fields=[
                ('scheduledtask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ninkasi.scheduledtask')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.milestonescheduledtask')),
            ],
            options={
                'abstract': False,
            },
            bases=('ninkasi.scheduledtask',),
        ),
        migrations.CreateModel(
            name='RepeatedTaskSub',
            fields=[
                ('scheduledtask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ninkasi.scheduledtask')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.repeatedscheduledtask')),
            ],
            options={
                'abstract': False,
            },
            bases=('ninkasi.scheduledtask',),
        ),
    ]
