# Generated by Django 4.2 on 2023-05-24 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.CharField(max_length=100, verbose_name='Nr')),
                ('beer', models.CharField(max_length=100, verbose_name='Beer')),
                ('volume', models.FloatField(blank=True, null=True, verbose_name='Volume in liters')),
            ],
            options={
                'verbose_name_plural': 'Batches',
                'ordering': ['nr'],
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Phases',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('volume', models.SmallIntegerField(verbose_name='Volume')),
                ('ttype', models.SmallIntegerField(choices=[(0, 'Fermentation'), (1, 'BBT'), (2, 'Lagering')], default=0, verbose_name='Type')),
            ],
            options={
                'verbose_name_plural': 'Tanks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BBT',
            fields=[
                ('tank_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ninkasi.tank')),
            ],
            options={
                'verbose_name_plural': 'BBTs',
            },
            bases=('ninkasi.tank',),
        ),
        migrations.CreateModel(
            name='CCT',
            fields=[
                ('tank_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ninkasi.tank')),
            ],
            options={
                'verbose_name_plural': 'CCTs',
            },
            bases=('ninkasi.tank',),
        ),
        migrations.CreateModel(
            name='LagerTank',
            fields=[
                ('tank_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ninkasi.tank')),
            ],
            options={
                'verbose_name_plural': 'Lager tanks',
            },
            bases=('ninkasi.tank',),
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Time')),
                ('quantity', models.SmallIntegerField(choices=[(0, 'Acidity'), (1, 'DO'), (2, 'Gravity'), (3, 'CO2'), (4, 'FAN')], verbose_name='Quantity')),
                ('unit', models.SmallIntegerField(choices=[(0, 'Ph'), (1, 'PPM'), (2, 'SG')], verbose_name='Unit')),
                ('value', models.FloatField(verbose_name='Value')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.batch')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.phase')),
            ],
        ),
        migrations.CreateModel(
            name='BatchTank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField(verbose_name='Date from')),
                ('date_to', models.DateTimeField(verbose_name='Date to')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.batch')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.tank')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='tank',
            field=models.ManyToManyField(through='ninkasi.BatchTank', to='ninkasi.tank'),
        ),
    ]
