# Generated by Django 5.0 on 2024-06-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninkasi', '0002_alter_product_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitycheck',
            name='constant',
            field=models.FloatField(blank=True, help_text='If the quantity can be specifed across recipes, define the projected value here.', null=True),
        ),
    ]
