# Generated by Django 5.0 on 2024-06-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninkasi', '0003_qualitycheck_constant'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitycheck',
            name='margin',
            field=models.FloatField(blank=True, help_text='Allow margin', null=True),
        ),
    ]
