# Generated by Django 5.0 on 2024-06-28 11:02

import django.db.models.deletion
import ninkasi.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninkasi', '0004_qualitycheck_margin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitycheck',
            name='constant',
            field=models.FloatField(blank=True, help_text='If the quantity can be specified as constant acrossrecipes, define the projected value here.', null=True),
        ),
        migrations.AlterField(
            model_name='qualitycheck',
            name='offset',
            field=ninkasi.models.fields.DurationField(default='0m', help_text='Offset to milestone. Use negative amounts to specify time before', max_length=10),
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('brew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.product')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.material')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.ManyToManyField(blank=True, null=True, through='ninkasi.ProductMaterial', to='ninkasi.material'),
        ),
    ]
