# Generated by Django 5.0 on 2024-06-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninkasi', '0005_alter_qualitycheck_constant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmaterial',
            old_name='brew',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='batchmaterial',
            name='batchnr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Batch Nr'),
        ),
        migrations.AlterField(
            model_name='brewmaterial',
            name='batchnr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Batch Nr'),
        ),
    ]
