# Generated by Django 5.1.5 on 2025-02-11 20:44

import ninkasi.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninkasi', '0006_rename_brew_productmaterial_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brewhouse',
            name='maintenance_schema',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='maintenance_schema',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='ttype',
        ),
        migrations.AlterField(
            model_name='style',
            name='color',
            field=ninkasi.models.fields.IntRangeField(help_text='Give EBC color as range <int>, <int>', max_length=10, verbose_name='Color'),
        ),
    ]
