# Generated by Django 5.1.5 on 2025-02-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninkasi', '0007_remove_brewhouse_maintenance_schema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
