# Generated by Django 5.1.5 on 2025-06-17 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninkasi', '0008_deliverable_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='brewhouse',
            name='warmup',
            field=models.FloatField(help_text='Time in minutes needed for 1 degree C warmup.', verbose_name='Warmup time per degree C'),
        ),
        migrations.CreateModel(
            name='BatchQualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projected', models.FloatField(blank=True, null=True)),
                ('margin', models.FloatField(default=0)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('actual', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.batch')),
                ('qc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.qualitycheck')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.brand')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.material')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.unit')),
            ],
            options={
                'ordering': ['material__name'],
            },
        ),
    ]
