# Generated by Django 5.1.5 on 2025-07-01 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninkasi', '0009_brand_alter_brewhouse_warmup_batchqualitycheck_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('batchnr', models.CharField(blank=True, max_length=100, null=True, verbose_name='Batch Nr')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.brand')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.material')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.unit')),
            ],
            options={
                'ordering': ['material__name'],
            },
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
