# Generated by Django 5.1.5 on 2025-07-02 17:05

import django.db.models.deletion
import ninkasi.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninkasi', '0010_alter_brand_name_inventoryitem_delete_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Malt',
            fields=[
                ('ingredient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ninkasi.ingredient')),
                ('color', ninkasi.models.fields.FloatRangeField(max_length=50)),
                ('proteine', ninkasi.models.fields.FloatRangeField(max_length=50)),
                ('moisture', ninkasi.models.fields.FloatRangeField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
            bases=('ninkasi.ingredient',),
        ),
        migrations.CreateModel(
            name='Hop',
            fields=[
                ('ingredient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ninkasi.ingredient')),
                ('alpha_acid', ninkasi.models.fields.FloatRangeField(max_length=50)),
                ('substitutes', models.ManyToManyField(to='ninkasi.hop')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=('ninkasi.ingredient',),
        ),
        migrations.CreateModel(
            name='HopProduct',
            fields=[
                ('ingredient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ninkasi.ingredient')),
                ('alpha_acid', ninkasi.models.fields.FloatRangeField(max_length=50)),
                ('form', models.SmallIntegerField(choices=[(0, 'Flower'), (1, 'Pellet T90'), (2, 'Pellet Cryo')])),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.hop')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.brand')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=('ninkasi.ingredient',),
        ),
        migrations.CreateModel(
            name='MaltProduct',
            fields=[
                ('ingredient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ninkasi.ingredient')),
                ('color', ninkasi.models.fields.FloatRangeField(max_length=50)),
                ('proteine', ninkasi.models.fields.FloatRangeField(max_length=50)),
                ('moisture', ninkasi.models.fields.FloatRangeField(max_length=50)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.malt')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.brand')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=('ninkasi.ingredient',),
        ),
    ]
