# Generated by Django 5.1.5 on 2025-07-02 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninkasi', '0011_malt_hop_hopproduct_maltproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ninkasi.brand'),
        ),
    ]
