# Generated by Django 5.1.5 on 2025-07-16 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninkasi', '0012_alter_inventoryitem_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['date'], 'verbose_name_plural': 'Batches'},
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='batchnr',
            field=models.CharField(max_length=100, verbose_name='Batch Nr'),
        ),
        migrations.CreateModel(
            name='MaltMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_malt', models.CharField(max_length=100)),
                ('to_malt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.malt')),
            ],
        ),
    ]
