# Generated by Django 5.1.5 on 2025-07-21 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninkasi', '0013_alter_batch_options_alter_inventoryitem_batchnr_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brew',
            options={'ordering': ['date', 'batch__nr'], 'verbose_name_plural': 'Brews'},
        ),
        migrations.AlterField(
            model_name='batchmaterial',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ninkasi.brand'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brewmaterial',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ninkasi.brand'),
        ),
    ]
