# Generated by Django 5.1.5 on 2025-07-23 17:53

import ninkasi.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninkasi', '0014_alter_brew_options_alter_batchmaterial_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hop',
            name='beta_acid',
            field=ninkasi.models.fields.FloatRangeField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hopproduct',
            name='beta_acid',
            field=ninkasi.models.fields.FloatRangeField(blank=True, max_length=50, null=True),
        ),
    ]
