# Generated by Django 5.1.5 on 2025-07-24 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninkasi', '0015_hop_beta_acid_hopproduct_beta_acid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brewqualitycheck',
            name='margin',
        ),
        migrations.RemoveField(
            model_name='brewqualitycheck',
            name='projected',
        ),
    ]
