# Generated by Django 5.1.5 on 2025-07-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninkasi', '0016_remove_brewqualitycheck_margin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brew',
            name='volume_projected',
            field=models.FloatField(default=300, verbose_name='Planned volume'),
            preserve_default=False,
        ),
    ]
