# Generated by Django 5.1.5 on 2025-07-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninkasi', '0017_brew_volume_projected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitycheck',
            name='margin',
            field=models.FloatField(default=0, help_text='Allow margin'),
        ),
    ]
