# Generated by Django 5.1.5 on 2025-07-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninkasi', '0018_alter_qualitycheck_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitycheck',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
