# Generated by Django 5.1.5 on 2025-07-27 13:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninkasi', '0019_qualitycheck_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch2Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.SmallIntegerField(choices=[(0, 0), (1, 1)])),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original', to='ninkasi.batch')),
                ('spawned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.batch')),
            ],
        ),
    ]
