# Generated by Django 5.1.5 on 2025-08-04 14:25

import django.db.models.deletion
import ninkasi.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninkasi', '0020_batch2batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yeast',
            fields=[
                ('ingredient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ninkasi.ingredient')),
                ('attenuation', ninkasi.models.fields.IntRangeField(max_length=50)),
                ('flocculation', models.SmallIntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')])),
            ],
            options={
                'ordering': ['name'],
            },
            bases=('ninkasi.ingredient',),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='category',
            field=models.SmallIntegerField(choices=[(0, 'Malt'), (1, 'Hop'), (2, 'Yeast'), (3, 'Other')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batch2batch',
            name='spawned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spawned', to='ninkasi.batch'),
        ),
        migrations.CreateModel(
            name='YeastProduct',
            fields=[
                ('ingredient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ninkasi.ingredient')),
                ('attenuation', ninkasi.models.fields.IntRangeField(max_length=50)),
                ('flocculation', models.SmallIntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')])),
                ('form', models.SmallIntegerField(choices=[(0, 'Dry'), (1, 'Liquid'), (2, 'Slurry')])),
                ('base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ninkasi.yeast')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninkasi.brand')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=('ninkasi.ingredient',),
        ),
        migrations.DeleteModel(
            name='Fermentable',
        ),
    ]
